# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='origin',
            field=models.BooleanField(default=True),
        ),
    ]
